language: c
compiler: gcc
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq check libjson0 libjson0-dev curl
script: 
  - "./autogen.sh"
  - "./configure"
  - "make check"
notifications:
  email:
    - freeman.wes@gmail.com
