language: c
compiler: gcc
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq check check-dev libjson0 libjson0-dev curl curl-dev
script: 
  - "./autogen.sh"
  - "./configure"
  - "make check"
notifications:
  email:
    - freeman.wes@gmail.com
